### ISSUE TITLE
Include linked bug in subiquity triage report

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/server-jenkins-jobs#115]
On, e.g., https://errors.ubuntu.com/problem/694a1c5cf6e4c5922e013a849abec18ede63f42e, you can see a link to https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1863033. It would be handy if our triage report showed this bug link if present.

**Comment by paride** [comment]
The fun I had before figuring out that jq does not support `if .. then .. else .. end` without the `else` clause...
